### ISSUE TITLE
Sidebar moving in 1709

### ISSUE THREAD

**Issue by WitchDoctorAmI** [ArcadeRenegade/SidebarDiagnostics#181]
Hey,
my sidebar startet moving after I installed update 1709. I provide you a video of the behaviour:
https://imgur.com/a/8oAiL

**1. Your Operating System**
Win 10 64bit Update 1709
**2. App Version**
3.4.5.
**3. Any Relevant Settings**
nope
**4. Steps to Reproduce**
After Windows boot the sidebar keeps wandering around, if I close it and open it manually it stays where it should.

**Comment by ArcadeRenegade** [comment]
This is the most... interesting... bug I have seen so far 😆 

This is going to be difficult to troubleshoot but I will try. Is 1709 an Insider build?

**Comment by WitchDoctorAmI** [comment]
Let's call it the Pacman bug, as it pushes all Windows/Desktop icons over. :)
Once it reched the Left side it stays there.
Another thing: when I close it right at windows startup and start it again manually it stays in place, but as soon as there opens a full screen window (i.e.: games) on my mainscreen it starts moving again.

1709 is not an insider build, its the Windows 10 fall creators update, which released this week.

**Comment by AvengerUK01** [comment]
Can confirm, definitely an interesting one!

Same behaviour for me on 1709

**Comment by ArcadeRenegade** [comment]
i tried upgrading to windows 1709 but it broke my PC and it rolled back. i'll try again so i can troubleshoot this.

**Comment by sjgsteve21** [comment]
Can confirm, same issue after 1709 - captured a vid of it in action. Also note that my taskbar becomes unresponsive (blue mouse wheel when hovering mouse over taskbar) when this happens. I had to disable run on startup and kill the program for now. https://youtu.be/qGnuvDq4ses

**Comment by Daisenki** [comment]
It happens when you use the setting always on top + reserve space... I'm on release build 1709 16299.98

**Comment by shotgun** [comment]
YEAH!
You've fixed it!
Thanks for taking the time. I've had the app. shuttered since the Win10 up-date.

**Comment by Daisenki** [comment]
The issue is NOT fixed with the new version 3.4.6! The sidebar is moving like the version before. Nothing is fixed.

**Comment by shotgun** [comment]
It's fixed at Boot for me, waking up from Sleep status (just found out), it's still traversing the screen.
Back in the box you go...

**Comment by Daisenki** [comment]
I have a clean Windows 10, the sidebar was not installed on my system since the last Windows installation. I install it now with 3.4.6 with the default setting and the first thing happens was that the sidebar glitching like the version before.

**Comment by KosmatPD** [comment]
Yup, I can also confirm the marching bar after 1709 update. Actually, my update did not take so I had to do clean install. I updated all drivers, and made sure everything was up to date as required, still no go. The side bar starts moving to the left on its own squashing everything in its path when I log in. I reinstalled couple times, the latest version 3.4.6 but to no avail. Hope it gets fixed, I LOVE this bar.

**Comment by NickPuljic** [comment]
I get the same issue where my bar moves across the screen. Additionally, when it reaches the other side of the screen my computer freezes. When I uncheck "Reserve Space" this behavior stops. Hope this gets fixed.

**Comment by despotak** [comment]
Sidebar Diagnostics: **v3.4.6**
OS: **Windows 10, version 1803, build 17666 (Insider Preview)**

Same issue. No matter witch monitor or which side (left or right), when "Reserve Space" is enabled it traverses the screen until it reaches the other side.

**Comment by KosmatPD** [comment]
despotak: THANK YOU for the info, I tried the suggestion and it WORKS like a charm now :-) I stayed at 1703 on my main rig since FEB so I could have the working sidebar diag lol I upgraded the rest of my computers but no sidebar and did not think about unchecking the "Reserve Space". Now I just reloaded my main rig to 1803 and uncheck the block and I have a working side bar, VERY HAPPY :-) I LOVE THIS APP !!! I feel "blind" without it. I hope it constitutes to get updated, I donated once, maybe I will donate again :-) to me this is an ESSENTIAL tool ! I looked for alternatives when I ran into the sliding across screen problem, but I found non that I so well integrated and convenient.

**Comment by Nosferatu-Dk** [comment]
Also have the same issue after sleep. 
If the tip works, im so donating :)
Love this app so much

**Comment by joshuahwang12** [comment]
Hello, I don't know if this is still being tracked but I am still getting this issue. Any updates/fixes that people know of?

**Comment by ArcadeRenegade** [comment]
I'm not getting the same issue on Windows 10 Pro v1803
Sorry guys :( I can't troubleshoot it if I can't replicate

**Comment by cah-98** [comment]
I have the same issue as described above, whenever i have reserve space enabled in the options i occasionally get the wandering bar that wont stop until it reaches the end of the screen. I have three screens and have it on one of my secondary screens, have tried both and it happens no matter which one the program is open on. 

The wandering bar seems to occur most often when i switch settings in the program or when the secondary screens refresh, for example when connecting/disconnecting another screen or loading a fullscreen program/game on the main monitor.

1. Your Operating System
Win 10 Pro 64bit Update 1803
2. App Version
3.4.6.
3. Any Relevant Settings
Reserve space enabled.

**Comment by despotak** [comment]
Finally fixed on version `3.5.1`. Anyone that had this problem, please upgrade and try out the newer version.

**Comment by ArcadeRenegade** [comment]
Great
